-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 26-Set-2018 às 17:03
-- Versão do servidor: 10.1.31-MariaDB
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `code_dota`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `categorias_tb`
--

CREATE TABLE `categorias_tb` (
  `id` int(11) NOT NULL,
  `nome` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `categorias_tb`
--

INSERT INTO `categorias_tb` (`id`, `nome`) VALUES
(1, 'Força'),
(2, 'Agilidade'),
(3, 'Inteligência');

-- --------------------------------------------------------

--
-- Estrutura da tabela `herois_tb`
--

CREATE TABLE `herois_tb` (
  `id` int(11) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `biografia` text NOT NULL,
  `nome_imagem` varchar(255) NOT NULL,
  `data_cadastro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `categoria_id` int(11) NOT NULL,
  `usuario_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `herois_tb`
--

INSERT INTO `herois_tb` (`id`, `nome`, `biografia`, `nome_imagem`, `data_cadastro`, `categoria_id`, `usuario_id`) VALUES
(1, 'Abaddon', 'A Fonte do Averno é a origem do poder de uma família, uma rachadura em pedras primitivas da qual vapores de poderes proféticos surgiram durante gerações. Cada recém-nascido na Casa Averno é banhado na neblina negra e sob este batismo eles recebem uma conexão às energias místicas dessa terra. Eles crescem com o pensamento de que são bárbaros protetores das suas tradições e dos costumes do reino enquanto, na verdade, são os protetores da própria Fonte. Os motivos da neblina, ninguém entende. Quando a criança Abaddon foi banhada na Fonte, dizem que algo deu errado. Nos olhos da criança brilhava uma luz de compreensão que assustou todas as pessoas presentes e fez com que os sacerdotes começassem a sussurrar uns aos outros. Ele foi criado com a expectativa total de seguir o caminho de todo outro descendente do Averno; treinar a guerrear, pois para que em momentos de necessidade ele possa liderar o exército da família em defesa das terras ancestrais. Mas Abaddon estava sempre seguindo o seu próprio caminho. Enquanto outros treinavam com armas, ele inclinou-se à meditação na presença da neblina. Ele bebeu profundamente dos vapores que eram emitidos na Fonte, aprendendo a mesclar o seu espírito com o poder que fluía sob a Casa e, assim, tornou-se uma criatura da neblina negra. Mas havia conflitos na Casa Averno; idosos e jovens acusando Abaddon de estar negligenciando as suas responsabilidades. Mas tais acusações cessaram quando Abaddon cavalgou à batalha e todos viram como os poderes da neblina forneceram-lhe um domínio sobre a vida e a morte, um domínio que nenhum lorde da Casa jamais viu antes.	', 'abaddon.jpg', '2018-08-29 20:05:33', 1, 1),
(2, 'Alchemist', 'A ciência sagrada da Quymica era uma tradição da família Darkbrew, mas nenhum deles havia demonstrado a criatividade, ambição e negligência do jovem Razzil. No entanto, quando a idade adulta chegou, ele deixou os negócios da família de lado para tentar fabricar ouro através da Alquimia. Em um ato de audácia característico da sua reputação, Razzil anunciou que ele transmutaria uma montanha inteira em ouro. Após duas décadas de pesquisas, gastos e preparação, ele falhou espetacularmente, logo vendo-se encarcerado pela grande destruição que o seu experimento forjou. Ainda assim, Razzil nunca aceitou um não como resposta e procurou fugir para continuar as suas pesquisas. Quando descobriu que o seu novo companheiro de cela era um feroz ogro, encontrou a oportunidade que precisava. Após convencer o ogro a não devorá-lo, Razzil começou a preparar uma mistura para ele beber, feito dos bolores e limos que cresciam nas pedras da prisão. Dentro de uma semana, ela parecia pronta. Quando o ogro bebeu a poção, ele entrou num acesso de fúria incontrolável, destruindo as barras da cela e quebrando tanto as paredes quanto os guardas. Eles logo se encontraram perdidos na floresta que circundava a cidade, com uma trilha de destroços atrás deles e nenhum sinal de perseguição. Passados os efeitos do tônico, o ogro parecia sereno, feliz e até ansioso. Resolvendo trabalhar juntos, o par começou uma jornada para coletar os materiais necessários para tentar a transmutação alquímica de Razzil mais uma vez.	', 'alchemist.jpg', '2018-08-30 16:47:29', 1, 1),
(3, 'Ancient Apparition', 'Kaldr, o Ancient Apparition, é uma imagem projetada de fora do tempo. Ele sai do vazio frio e infinito que precede e aguarda o fim do universo. Kaldr é, Kaldr foi, Kaldr será... e o que percebemos, poderoso como parece a nós, não passa do mais fraco eco desbotado do verdadeiro e eterno Kaldr. Alguns acreditam que enquanto o cosmos envelhecer e aproximar-se dos seus momentos finais, a luz e o poder do Kaldr também se intensificará – que o Ancient Apparition tornará-se mais jovem e forte à medida que o fim da eternidade se aproxima. O seu punho de gelo tornará toda a matéria estática, a sua imagem lançará uma luz terrível demais para se ver. Não mais uma aparição!	', 'ancient-apparition.jpg', '2018-08-30 19:09:22', 3, 1),
(9, 'Anti Mage', 'Os monges de Turstarkuri observavam os vales escarpados abaixo do seu monastério na montanha, enquanto hordas após hordas de invasores passavam pelos reinos inferiores. Ascéticos e pragmáticos, mantinham-se indiferentes a conflitos mundanos no seu remoto ninho monástico, envoltos em uma meditação que não conhecia deuses ou elementos de magia. Então veio a Legião do Deus Morto, cruzados com o sinistro mandato de substituir todo culto local pela niilosofia venenosa do seu Senhor Sem-vida. De uma paisagem que não conheceu nada além de sangue e batalha por mil anos, eles arrancaram as almas e ossos de incontáveis legiões caídas e os lançaram contra Turstarkuri. O monastério mal conseguiu resistir ao ataque por uma quinzena, e os poucos monges que se deram ao trabalho de sair da sua meditação acreditavam que os invasores eram apenas visões demoníacas enviadas para distraí-los das suas contemplações. Eles morreram sentados nas suas almofadas de seda. Apenas um jovem sobreviveu – um peregrino que foi recebido como um acólito, buscando sabedoria, mas que ainda estava para ser admitido no monastério. Ele assistiu com horror enquanto os monges a quem tinha servido chá e urtigas eram massacrados e então reerguidos para se juntar às hostes sacerdotais do Deus Morto. Com pouco mais que alguns estimados pergaminhos dogmáticos dos Turstarkuri, ele escapou sem ser visto para a relativa segurança de outras terras, jurando não somente obliterar os usuários de magia do Deus Morto – mas pôr um fim à magia como um todo.	', 'anti-mage.jpg', '2018-08-30 19:11:40', 2, 1),
(10, 'Arc Warden', 'Antes do começo de tudo, existia uma presença: uma mente primordial, infinita, fantástica e com um propósito inescrutável. À medida que o universo tomava forma, esta mente foi fragmentada e disseminada. Dois dos seus maiores fragmentos — que passariam a ser chamados de Iluminado e Temido — se encontraram presos a uma oposição violenta e começaram a moldar toda a criação para servir ao seu conflito.\r\n\r\n\r\n\r\nConforme a guerra e o cataclismo ameaçaram o cosmo nascente, a vontade de um terceiro fragmento se fez conhecida. Tomando o nome de Zet, este intelecto procurou resolver a desarmonia e retornar tudo à perfeita união. Chocado pela natureza conflituosa dos seus semelhantes, Zet coletou a soma de seus poderes. Em um clarão repentino, ele prevaleceu perante os seus semelhantes e fundiu os aspectos antagônicos em uma esfera estelar antes de lançá-los na escuridão para orbitar um mundo desconhecido. A harmonia foi restaurada, no entanto apenas uma pequena fração da força de Zet restou. Fixando o seu olhar na prisão, Zet escolheu usar o seu poder enfraquecido para servir como um guardião vigilante até o fim dos tempos. Por incontáveis éons, esta vigília permaneceu.\r\n\r\n\r\n\r\nA vida floresceu no mundo abaixo, alheia aos perigos aprisionados na lua de brilho suave ou do esforço de Zet para contê-los. Enquanto o conflito eterno dos prisioneiros reverberava no interior, a superfície da prisão estremecia e com o tempo começou a rachar. Ultimamente, o poder esgotado de Zet provou-se insuficiente para conter a fenda e finalmente a lua foi despedaçada. Os habitantes da prisão escaparam, prontos para disseminar o seu conflito mais uma vez.\r\n\r\n\r\n\r\nArremessado para os recantos mais distantes pela explosão da prisão, Zet foi transformado pelas energias dissonantes dos seus antigos prisioneiros. Não possuindo mais uma só forma e mente, a sua presença foi dividida em muitas — algumas menores, outras maiores — unidas entre si por um arco fugaz de consciência. Lutando para reprimir a sua própria desunião, Zet apressou-se em direção ao conflito que ressurgia entre os seus semelhantes, moldando as suas vontades fraturadas para uma só conclusão: os aspectos da mente primordial devem ser reunidos ou tudo deve ser destruído para que o conflito não se espalhe mais...	', 'arc-warden.jpg', '2018-08-30 19:13:59', 2, 1),
(11, 'Axe', 'Mesmo quando soldado de baixa patente do Exército da Névoa Vermelha, Mogul Khan ambicionava a patente de General da Névoa Vermelha. Batalha após batalha, ele provou o seu valor através dos seus atos violentos. A sua ascensão pelas patentes foi ajudada pelo fato dele nunca hesitar em decapitar um superior. Durante os sete anos da Campanha dos Mil Lagos, destacou-se dos outros em gloriosos massacres, a sua estrela da fama brilhando cada vez mais enquanto o número de companheiros de armas minguava constantemente. Na noite da vitória suprema, o Axe declarou-se o novo General da Névoa Vermelha e tomou o título máximo de \"Axe\". Mas os números das suas tropas haviam chegado a zero. Claro, muitos morreram em batalha, mas um número significativo também caíra pela lâmina de Axe. Desnecessário dizer, agora a maioria dos soldados evita a sua liderança. Mas isso é insignificante para Axe, que sabe que um exército de um homem só é, sem dúvida, o melhor.	', 'axe.jpg', '2018-08-30 19:15:09', 1, 1),
(12, 'Bane', 'Quando os deuses têm pesadelos, é o Bane Elemental que os traz. Também conhecido como Atropos, Bane nasceu a partir dos terrores da meia-noite da deusa Nyctasha. Sendo uma força de terror poderosa demais para ser contida em sonhos, ele veio ao mundo através dos seus torpores, alimentou-se da sua imortalidade e tomou a sua forma nebulosa do sangue escuro dela. Ele é a essência do medo. Mortais que ouvem a sua voz escutam os seus segredos mais sombrios sussurrados nos seus ouvidos. Ele chama pelo medo oculto no coração de cada herói. Ficar acordado não traz proteção, pois o sangue negro e sempre gotejante de Bane é um piche que prende os seus inimigos em pesadelos. Na presença de Bane, nenhum herói se esquece de temer o escuro.	', 'bane.jpg', '2018-08-30 19:16:07', 3, 1),
(13, 'Batrider', 'Algo que não existe entre as criaturas da Selva Yama Raskav é harmonia. Seja por dentada, garra, pinça ou casco, até mesmo o menor sinal de fraqueza significa uma morte rápida. Dizem que o Rider era apenas um moço que cortava palha no terreno da sua família quando foi levado, agarrado por um mordecego à procura de presas. Mas este rapaz teve uma ideia melhor, e retorceu-se desde o aperto do seu raptor para as costas da besta, e dilacerou-o até cair com as suas ferramentas. Emergindo dos destroços sangrentos e intoxicado pela emoção do voo, o rapaz percebeu que tinha encontrado a sua vocação. O rapaz cresceu e a cada verão regressou aos terrenos da sua família, indo regularmente para os arbustos à procura daquela primeira emoção de encarar a morte na forma de mandíbulas ou de uma queda fatal. Os anos passaram, mas o seu fulgor apenas aumentou. Ele estudou a selva, mergulhando cada vez mais profundamente com cada expedição, até que finalmente encontrou as cavernas no coração da hostilidade. Diz-se que o Rider, na véspera de uma noite de verão escaldante, não tinha nada além de uma corda, uma garrafa de coragem líquida e uma determinação ardente de voltar a sentir os céus mais uma vez, quando ele entrou apressadamente...	', 'batrider.jpg', '2018-08-30 19:17:09', 3, 1),
(14, 'Beastmaster', 'Karroch cresceu sem família. A sua mãe morreu ao lhe dar a luz. O seu pai, um ferrador a serviço do Último Rei de Slom, foi pisoteado até à morte quando ele tinha cinco anos. Mais tarde, Karroch foi obrigado a trabalhar como tratador na coleção de animais do rei, onde cresceu no meio das feras da corte real: leões, macacos, veados demoníacos e criaturas menos conhecidas, as quais mal acreditava-se existirem. Quando o rapaz tinha sete anos, um explorador trouxe uma fera nunca antes vista. Arrastada em correntes até ao Rei, a fera falou, mas a sua boca não se moveu. As suas palavras: um apelo por liberdade. O Rei apenas riu e ordenou que a fera atuasse para o seu divertimento; e quando ela recusou, o rei bateu-lhe com o seu Cetro da Loucura e ordenou que fosse arrastada para junto das outras feras. Durante meses, Karroch levava comida e medicamentos às escondidas à criatura ferida, mas isso apenas atrasava a sua deterioração. Sem usar palavras, a fera falava com o rapaz, e ao longo do tempo o seu laço se fortaleceu até que o rapaz percebeu também ser capaz de poder se comunicar de volta. Ele podia, agora, falar com todas as criaturas da coleção do rei. Na noite em que a fera morreu, uma fúria tomou conta do rapaz. Ele incentivou os animais da corte a se rebelarem e abriu as suas jaulas para que libertassem a sua fúria pelo palácio. O Último Rei foi massacrado na confusão. No meio de todo o caos, um veado real ajoelhou-se perante o rapaz que o tinha libertado; e com o Beastmaster montado nele, saltou por cima das altas muralhas do castelo e escapou. Agora um homem, Karroch, o Beastmaster, não perdeu a sua habilidade de conversar com criaturas selvagens. Ele tornou-se um guerreiro em sinergia com a selvageria da natureza.	', 'beastmaster.jpg', '2018-09-04 13:12:43', 1, 1),
(15, 'Bloodseeker', 'Strygwyr, o Bloodseeker, é um caçador autorizado por ritual, o Cão de Caça dos Gêmeos Esfolados, enviado dos picos enevoados de Xhacatocatl em busca de sangue. Os Esfolados requerem quantidades oceânicas de sangue para se manterem saciados e apaziguados, e em breve sugariam a sua população do seu império montanhoso se os sacerdotes dos elevados planaltos não os satisfizessem. Strygwyr, portanto, vai à procura de carnificina. A energia vital de qualquer sangue que ele derrama flui imediatamente para os Gêmeos através das marcas sagradas nas suas armas e armadura. Ao longo dos anos, ele passou a encorporar a energia de uma fera perversa; em batalha ele é selvagem como um chacal. Por trás da Máscara do Bloodseeker, na afobação de saciamento de sangue, diz-se que por vezes se pode ver os traços dos Esfolados tomando posse direta do seu Cão de Caça.	', 'bloodseeker.jpg', '2018-09-04 17:51:06', 2, 1),
(16, 'Bounty Hunter', 'Quando os caçados contam histórias de Gondar, o Bounty Hunter, ninguém está certo de quais são verdadeiras. Em tons sussurrados dizem que foi abandonado quando criança, aprendendo a sua habilidade de rastreamento como uma simples questão de sobrevivência. Outros ouvem que ele foi um órfão de guerra, tomado pelo grande Soruq, o Caçador, para aprender a habilidade do mestre com uma lâmina enquanto sondavam florestas escuras em busca de uma boa caça. Outros ainda acreditam que ele era um moleque de rua criado entre uma guilda de batedores de carteira e ladrões, treinado nas artes de furtividade e esquiva. Ao redor de fogueiras na selvagem área rural, a sua vítima fala de rumores do trabalho de Gondar, cada vez mais temível: dizem que foi ele quem rastreou o tirano Rei Goff anos antes do regente louco procurar esconderijo, entregando a sua cabeça e cetro como provas. Que foi ele quem se infiltrou nos campos rebeldes em Alto Trono, finalmente trazendo o lendário Capa Branca para ser julgado pelos seus crimes. E que foi ele quem acabou com a carreira de Soruq, o Caçador, condenado como criminoso por matar o precioso milhano infernal do príncipe. As histórias da incrível perícia de Gondar se estendem, com cada feito ousado mais inacreditável que o outro, cada alvo mais evasivo. Pelo preço certo, a vítima sabe, qualquer um pode ser encontrado. Pelo preço certo, até os mais poderosos podem encontrar medo nas sombras.	', 'bounty-hunter.jpg', '2018-09-04 17:54:51', 2, 1),
(17, 'Brewmaster', 'Nas profundezas das Montanhas da Lamentação, em um vale abaixo da Cidade Arruinada, a antiga Ordem do Oyo tem praticado por séculos os seus ritos de devaneios sagrados, comungando com o reino espiritual em grandes festivais de bebida. Concebido da carne de uma mãe por um pai celestial, o jovem conhecido como Mangix foi o primeiro a nascer com os talentos de ambas as linhagens. Ele treinou com os maiores estéticos da Ordem, logo recebendo, pela assídua ebriedade, o direito de concorrer ao título de Brewmaster; título de grande reputação dentro da contemplativa seita fermentadora de malte. Tanto competição de bebida quanto combate mortal, Mangix bebeu e lutou contra o mestre ancião por nove dias. Por nove noites eles cambalearam e rodopiaram, bradaram e combateram, até que finalmente o guerreiro ancião caiu num estupor bêbado, e um novo Brewmaster foi nomeado. Agora o novo e jovem Brewmaster clama pela força dos seus antepassados do Oyo para amparar o seu cajado. Quando pratica magia, é para os seus espíritos ancestrais que ele se volta. Como todos os Brewmasters anteriores, ele foi enviado pelo seu povo com uma única missão. Ele vaga pelas terras empenhando-se em obter iluminação através da bebida, buscando uma resposta para a antiga segregação espiritual — esperando conceber o pensamento que unirá os planos físico e espiritual novamente.	', 'brewmaster.jpg', '2018-09-04 17:56:23', 1, 1),
(18, 'Bristleback', 'Nunca do tipo que dava as costas em uma briga, Rigwarl era famoso por lutar contra os maiores e mais malévolos desordeiros em que ele conseguia botar as suas mãos. Batizado com o nome de Bristleback pelas multidões embriagadas, cambaleava em direção a batalhas nos fundos de cada taverna na estrada entre Slom e Elze, até que o seu comportamento abusivo finalmente chamou a atenção de um dono de bar que estava em busca de um capanga. Por um pouco de bebida, o Bristleback foi contratado para receber contas, manter a paz e, de vez em quando, quebrar um osso ou dois (ou cinco, no caso de um certo azarado). Depois de ir além da conta em uma noite de farra durante a qual dores corporais foram distribuídas igualmente sobre fregueses delinquentes e o seu próprio fígado, o Bristleback finalmente encontrou o seu páreo. \"As suas presas me ofendem, senhor\", ouviu-se ele bêbado difamar contra um camarada particularmente grande vindo do norte e que não queria pagar a conta. O que se seguiu foi a maior briga de todos os tempos. Uma dúzia de encrenqueiros partiu para a luta. Nenhuma cadeira permaneceu inteira e, no fim, o impossível aconteceu: a conta não foi paga. Nas semanas que se seguiram, as feridas de Bristleback sararam e os seus espinhos cresceram de volta; mas a honra de um capanga pode ser algo bem caro. Ele pagou a conta com as suas próprias moedas, jurando encontrar aquela figura do norte e conseguir a sua vingança. E então ele fez algo que nunca teria feito antes: treinou. E, durante o seu treinamento, fez uma descoberta espantosa sobre si mesmo. Um sorriso alargou-se até os seus dentes mais fundos enquanto ele flexionava os seus espinhos. Dar as costas em uma briga pode acabar sendo a melhor escolha.	', 'bristleback.jpg', '2018-09-04 17:57:52', 1, 1),
(19, 'Broodmother', 'Durante séculos, Black Arachnia, a Broodmother, escondeu-se nos escuros tubos de lava abaixo da caldeira escaldante do Monte Pyrotheos, criando milhões de crias em segurança antes de as mandar caçar no mundo selvagem à superfície. Após um tempo, o Vizir da Ganância, Ptholopthales, ergueu o seu zigurate de pedra-ímã nas vertentes do vulcão adormecido, sabendo que quaisquer saqueadores que procurassem a sua riqueza magnética teriam que sobreviver às passagens repletas de aranhas. Passados milênios de paz materna, Black Arachnia deu por si incomodada por um caminhar estável de pés-de-lã e de ladrões de bolsas, cavaleiros corajosos e jovem nobreza – todos eles deliciosos, certamente, e no entanto tendiam a criar um ambiente menos nutricional que a sua prole inocente. Cansada de intrusões, fez uma visita a Ptholopthales; e quando ele se provou relutante em estabelecer um acordo, enrolou-o em seda e colocou-o de parte para ser a peça central de um banquete especial de aniversário. Infelizmente, a ausência do mestre do Zigurate Magnético apenas encorajou uma nova geração de intrusos. Quando uma das suas recém-nascidas aranhas foi espezinhada por um aventureiro trapalhão, ela chegou ao fim da sua corda sedosa. A Broodmother dirigiu-se à superfície, declarando a sua intenção de ver o mundo livre de todos e cada um dos possíveis invasores, até do último herói se assim fosse preciso, até que ela pudesse garantir que o seu berçário teria novamente um ambiente seguro e saudável para as suas preciosas ovas de aranha.	', 'broodmother.jpg', '2018-09-04 17:58:41', 2, 1),
(20, 'Centaur Warrunner', 'Diz-se que a estrada de um centauro é pavimentada com os cadáveres dos derrotados. Para aquele a quem chamam Warrunner, foi mesmo uma longa estrada. Para forasteiros, os clãs quadrúpedes de Druud são equivocadamente tomados por criaturas simples e selvagens. A sua língua não tem escrita; a sua cultura falta tradições pictográficas, música estruturada e religião formalizada. Para centauros, combate é a articulação perfeita do pensamento, a maior expressão de si. Se matar é uma arte entre centauros, então Bradwarden é o melhor dos seus artistas. Ele emergiu à dominância em Omexe, uma antiga arena onde clãs de centauros se reúnem há milênios para lutar pelos seus direitos gladiatórios. Conforme a sua fama se espalhava, espectadores vinham de todos os cantos a fim de ver o grande centauro em ação. Sempre o primeiro a pôr os pés na arena e o último a sair, ele compõe uma obra-prima a cada jorrada, cada corte do comprimento de uma lâmina ensebada de sangue. É a poesia de sangue em ferro, arremessada em padrões complexos através de areias pálidas do matadouro. Warrunner derrotou guerreiro após guerreiro, até que a arena explodiu com as ovações no seu nome, e ele encontrou-se sozinho, o invicto campeão da sua espécie. O grande cinturão de Omexe lhe foi concedido, envolvendo o seu largo tronco, mas na sua vitória, o artista da morte encontrou apenas um sentimento vazio. Pois o que é um guerreiro sem desafios? O grande centauro galopou para fora de Omexe naquele dia com um novo objetivo. Para o seu povo, Warrunner é o maior guerreiro que já pisou na arena. Agora ele se foi para provar que é o maior lutador que já viveu.	', 'centaur-warrunner.jpg', '2018-09-04 17:59:38', 1, 1),
(21, 'Chaos Knight', 'O veterano de incontáveis batalhas em mil mundos, o Chaos Knight vem de um plano distante onde as leis fundamentais do universo encontraram expressão consciente. De todos os Fundamentais ancestrais, ele é o mais velho e mais infatigável, sempre em busca de um ser que ele conhece apenas como \"A Luz\". Há muito tempo a Luz aventurou-se para fora do reino progenitor, em desafio da primeira aliança. Agora o Chaos Knight vai de plano a plano, sempre na caça para extinguir a Luz onde quer que a encontre. Mil vezes ele eliminou a fonte, e sempre desliza para outro plano para continuar a sua busca. Sobre a sua montaria, o Armagedom, ele cavalga, entrando na batalha em fúria obsessiva, sugando forças do caos do universo. Uma manifestação física do caos em si, ele traz as outras versões de si de outros planos em momentos de necessidade e juntos esses cavaleiros cavalgam em direção a batalha, tão imbatíveis quanto qualquer outra força da natureza. Apenas quando a última Luz do mundo for eliminada da existência a sua busca será terminada. Onde cavalga o Chaos Knight, a morte segue.	', 'chaos-knight.jpg', '2018-09-04 18:01:40', 1, 1),
(22, 'Chein', 'Nascido nas inóspitas terras áridas de Hazhadal, Chen atingiu a maioridade entre as tribos foragidas que sobreviviam no calor difuso do deserto. Usando uma forma antiga de encantamento de animais, o povo de Chen amestrava os locuthi robustos do deserto, uma espécie atrofiada de dragões subterrâneos que derretia as areias do deserto em tubos de vidro, onde a água da chuva se acumulava duas vezes ao ano. Sempre à beira de morrer de fome e de sede, lutando ao lado dos seus vizinhos e uns contra os outros, o clã de Chen cometeu o erro, em um dia fatídico, de emboscar a caravana errada. Na batalha viciosa que se seguiu, o clã de Chen foi derrotado. Os blindados Cavaleiros da Dobra acabaram com os locuthi encantados rapidamente, que atacaram e morreram um após o outro. Com os seus dragões mortos, os homens da tribo seguiram-se. Chen debateu-se e cortou, arranhou, matou – ou teria morrido. Derrotado, de joelhos, encarou a sua execução humildemente, oferecendo o seu pescoço à lâmina. Movido pela coragem óbvia de Chen, o carrasco parou a espada no ar. Em vez da lâmina, foi dada a Chen uma escolha: morte ou conversão. Chen aceitou a doutrina com ferocidade. Juntou-se à Dobra e fez por merecer a sua armadura, uma conversão sangrenta de cada vez. Agora, com o fanatismo de um convertido e com os seus poderes de encantamento animal no seu máximo esplendor, ele procura descrentes e introduz-lhes às suas recompensas finais.	', 'chen.jpg', '2018-09-04 18:04:13', 3, 1),
(23, 'Clinkz', 'Na encosta das Colinas Sangrentas se estende uma floresta de mil léguas — um lugar chamado Hoven, onde charcos negros juntam o sangue coberto de piche dos planaltos, e o mago-rei Sutherex domina benevolentemente. Outrora um protetor jurado das terras de Hoven, Clinkz ganhou uma reputação pela sua habilidade com o arco. No trecentésimo ano do mago-rei Sutherex, o demônio Maraxiform ergueu-se do sexto inferno para tomar posse da floresta. Em resposta, o mago-rei lançou um feitiço inquebrável: aquele que matasse o demônio teria garantida a Vida Sem Fim. Inconsciente do feitiço, Clinkz seguiu para a batalha, defendendo as suas terras contra o ataque feroz do demônio. Clinkz enviou Maraxiform de volta para os portões do sexto inferno, onde naquele feroz limiar os dois investiram em um conflito mortal. Gravemente ferido, o demônio lançou uma rajada de fogo infernal enquanto Clinkz lançou a sua última flecha. A flecha acertou o demônio em cheio no momento em que o fogo infernal fluiu através da terra, iluminando os charcos negros e queimando Clinkz vivo no momento da morte do demônio. Mas o feitiço do mago teve efeito no momento exato da conflagração do arqueiro, preservando-o neste estado profano, deixando-o como um ser de ossos e fúria, pego entre a morte e a vida, carregando o respiro do inferno com ele na sua jornada para a eternidade.	', 'clinkz.jpg', '2018-09-04 18:04:52', 2, 1),
(24, 'Clockwerk', 'Rattletrap possui os mesmos ancestrais longínquos do Sniper e do Tinker e, da mesma forma como muitos outros do povo Keen, ele compensou a sua pequena estatura com o uso de geringonças e astúcia. O filho de um filho de um relojoeiro, Rattletrap passou muitos anos como aprendiz dessa profissão antes da guerra descer as montanhas e varrer as vilas da planície das suas vocações inocentes. \"O seu novo ofício é a batalha\", o seu pai moribundo o disse enquanto a vila dos seus ancestrais se incendiava e se transformava em ruínas. Um artesão pobre culpa as suas ferramentas, mas Rattletrap nunca foi de inventar desculpas. Depois de enterrar o seu pai entre as ruínas da sua vila, ele decidiu transformar-se no maior instrumento de guerra que o mundo já viu. Ele jurou nunca ser pego despreparado; assim, usando os seus talentos, construiu uma poderosa armadura Clockwerk que fazia com que os cavaleiros de outras terras parecessem latinhas. Agora Rattletrap vive com aparelhos. Um pequeno, mas letal guerreiro cujas habilidades de emboscada e destruição se elevaram a níveis de eficiência quase mecânicos. Como um artífice da morte, as suas mecanizações lidam facilmente com os distraídos, anunciando uma nova aurora para esta era bélica. Que horas são? É hora do Clockwerk!	', 'clockwerk.jpg', '2018-09-04 18:07:12', 1, 1),
(25, 'Crystal Maiden', 'Nascida em uma região de clima temperado e criada com a sua escaldante irmã mais velha Lina, Rylai, conhecida como a Crystal Maiden, rapidamente descobriu que a sua inata afinidade elementar para o gelo criava problemas para todos à sua volta. Nascentes e rios de montanha congelavam em momentos se ela parava ao pé deles para descansar; colheitas que estavam amadurecendo eram atingidas pela geada e pomares cheios de frutos transformavam-se em labirintos de gelo e acabavam por se arruinar, estragados. Quando os seus pais exasperados enviaram Lina para o equador, Rylai encontrou-se exilada na região fria e nortenha de Geleiras Devastadas, onde foi abrigada por um Feiticeiro do Gelo que tinha esculpido para si próprio um eremitério no ponto mais alto da Geleira Coração Azul. Após um longo período de estudo, o feiticeiro declarou que ela estava pronta para praticar sozinha e deixou-a tomar o seu lugar, descendo à geleira para hibernar durante mil anos. O seu controle das Artes do Gelo apenas tem aumentado desde então, e agora as suas habilidades são inigualáveis.	', 'crystal-maiden.jpg', '2018-09-04 18:07:43', 3, 1),
(26, 'Dark Seer', 'Veloz quando necessário e um estrategista astuto, Ish\'Kafel, o Dark Seer, dispensa qualquer arma afiada para derrotar os seus inimigos, dependendo, em vez disso, da força da sua poderosa mente. O seu talento reside na habilidade de manipular a luta à sua maneira. Vindo de um lugar que ele chama de \"A Terra por Trás da Parede\", o Dark Seer mantém-se como um forasteiro aqui – um guerreiro de uma dimensão além do véu desta realidade. Outrora um grande general entre o seu povo e um valente defensor do rei-deus Damathryx, o exército do Dark Seer foi eliminado por uma força muito maior nos dias finais da Guerra das Fronteiras Desmedidas. Ao encarar a derrota certa, ele fez um último ato desesperado: conduziu as forças inimigas para o labirinto entre as paredes. No último segundo, momentos antes de ser capturado, ele atravessou as paredes e depois as selou para sempre em uma explosão de energia negra. Quando a poeira baixou, ele percebeu que havia salvo o seu povo, mas viu-se agora debaixo de um sol em um mundo diferente, sem volta. Agora ele está comprometido a provar o seu valor como estrategista militar, jurando demonstrar ser o maior tático que este estranho mundo novo outrora viu.	', 'dark-seer.jpg', '2018-09-04 18:08:11', 3, 1),
(27, 'Dark Willow', 'Crianças adoram contar histórias sobre aventuras fantásticas de fadas... Isso porque as crianças não sabem que a maioria das fadas são seres idiotas e rancorosos. E no mundo das fadas rancorosas há poucos nomes mais desprezados do que Mireska Sunbreeze.\r\n\r\nFilha de um rei comerciante, Mireska cresceu em Revtel; uma nação sem lei onde manipulação e assassinato eram a norma. Porém, embora ela fosse adepta de seguir a etiqueta, tradições e rituais sociais que permeavam cada momento da sua vida, ela acabou cansando de tudo aquilo.\r\n\r\nEntão, Mireska fez o que a maioria das crianças rebeldes fazem: queimou toda a propriedade da sua família e partiu com o seu espírito de estimação Jex para levar uma vida errante.	', 'dark-willow.jpg', '2018-09-04 18:12:07', 3, 1),
(28, 'Dazzle', 'Cada novo acólito da Ordem Dezun tem de completar uma série de ritos antes de se tornar um sacerdote das sombras. A cerimônia final, o rito das sombras, é uma jornada espiritual agonizante pelo Reino Nothl, terras imprevisíveis de onde nem todos os visitantes retornam. Daqueles que o conseguem fazer, alguns voltam loucos. Outros voltam com aptidões estranhas. Mas todos os que vão para lá sofrem alterações com as suas experiências. Impulsionado pela necessidade de esclarecimento, Dazzle foi o mais novo da sua tribo a pedir o sagrado ritual. Da primeira vez a ordem recusou o seu pedido, dizendo que ele era jovem demais. Mas Dazzle não ia ser dissuadido. Sentindo algo de especial no acólito novo e teimoso, os anciões cederam. Dazzle bebeu a poção sagrada e sentou-se ao lado da fogueira enquanto o resto da tribo dançava noite adentro. Nesta dimensão etérea do Reino de Nothl, as propriedades da luz e da escuridão são invertidas. Assim, a sua brilhante luz curativa, bonita para os nossos olhos, é na verdade um tipo de mal sinistro; e as ações mais obscuras são feitas num brilho deslumbrante. As intuições dos anciões eram proféticas: Dazzle voltou para o seu povo como um Padre das Sombras como nunca nenhum outro antes visto, com o poder de curar assim como de destruir. Agora ele usa o seu poder para ferir os seus inimigos e remendar os seus amigos.	\r\n', 'dazzle.jpg', '2018-09-04 18:12:38', 3, 1),
(29, 'Death Prophet', 'Krobelus era uma Death Prophet – o que é uma maneira de dizer que ela fazia previsões para os mais ricos daqueles que desejavam olhar além do véu. Mas após anos de indagações em nome de terceiros, ela começou a procurar pistas do próprio destino. Quando a Morte recusou-se a revelar os seus segredos, ela tentou comprá-los com a sua vida. Mas o maior preço provou-se insuficiente. A Morte a regurgitava de novo e de novo, sempre guardando os seus mistérios mais profundos. A sua inveja cresceu. Outros podiam morrer pela eternidade – por que não ela? Por que ela somente deve ser lançada às margens da vida com tão cansativa regularidade? Por que ela não era digna da única coisa que é garantida a todas as outras criaturas viventes? Mesmo assim, ela não se desencorajaria. Cada vez que voltava do túmulo, ela trazia consigo um pouco de morte. Espectros a seguiam como fragmentos da sua alma estilhaçada; o seu sangue diluiu-se e tornou-se ectoplasmático; as criaturas famintas do crepúsculo tomaram-na como uma deles... Ela deu um pouco da sua vida com cada falecimento, e começou a parecer que o seu fim estava à vista. Com a sua dedicação à morte redobrada, e nenhum cliente que não ela mesma, Krobelus jogou-se ainda mais fervorosamente ao abismo da morte, concentrada em completar a única profecia que lhe escapou: que algum dia a Death Prophet não voltaria da morte nunca mais.	', 'death-prophet.jpg', '2018-09-04 18:13:07', 3, 1),
(30, 'Disruptor', 'No alto das estepes devastadas de Druud, um jovem talentoso dos Stormcrafters chamado Disruptor foi o primeiro a descobrir os segredos das rajadas de verão. Constantemente sob ataque, tanto de tempestades sazonais quanto de invasões dos reinos civilizados ao sul, os Oglodi das montanhas lutaram por séculos pela subsistência no topo dos seus vastos planaltos. Eles são o resquício de uma outrora grande civilização, uma tribo arruinada, o seu ofício da tempestade estranho e inescrutável, remendada a partir de restos de conhecimento perdido que nem eles mesmos conseguem entender. Para aqueles dos planaltos, o clima tornou-se uma espécie de religião, venerado como aquilo que dá e toma a vida. Mas as tempestades elétricas que trazem as chuvas da vida vem com um custo, e muitos são os corpos queimados e fumegantes deixados como rastro. Apesar de pequeno para a sua espécie, o Disruptor era destemido, guiado por uma curiosidade insaciável. Embora ainda não fosse marcado por sangue, nem possuísse um trípode, ele explorou as ruínas das cidades ancestrais – pesquisando em bibliotecas desmoronadas e há muito se desfazendo e vasculhando fábricas enferrujadas. Ele pegou o que precisava e retornou à sua tribo. Adaptando uma bobina de modelo antiquado, ele dominou o poder do diferencial elétrico e agora chama os trovões quando lhe convém. Parte mágica, parte perícia, as suas bobinas guardam nas suas placas brilhantes o poder da vida e da morte – um poder empunhado com precisão contra as castas das planícies ao sul e qualquer intruso que cruzar as terras anciãs dos Oglodi.	\r\n', 'disruptor.jpg', '2018-09-04 18:13:28', 3, 1),
(31, 'Doom', 'Aquele que arde em chamas mas não é consumido, que devora mas nunca está saciado, mata mas está acima de qualquer julgamento – Lucifer condena todos que ousam enfrentá-lo. Removendo as almas que estão na ponta da sua impetuosa espada, ele é o Caído, um general antes favorecido do reino além da luz, expulso pelo pecado da rebeldia: ele não se ajoelharia. O seu nome soou seis vezes do grande sino de Vashundol. Seiscentas e sessenta vezes as suas asas foram marcadas em brasa, até que só sobrassem cinzas. Sem asas, ele se soltou das amarras que o ligavam à luz e ele caiu, gritando, na terra. Uma cratera no deserto, o Paraíso perdido. Agora ele ataca sem misericórdia, sem motivo, o único ser vivo capas de se mover livremente entre os sete domínios das trevas. Amarrado por necessidades incontroláveis e alterado por talentos inimagináveis, o Doom carrega o seu próprio inferno com ele para qualquer lugar. Desafiador até o fim. Mais cedo ou mais tarde, o mundo será do seu domínio.	', 'doom.jpg', '2018-09-04 18:13:46', 1, 1),
(32, 'Dragon Knight', 'Após anos no rastro de um ancivorme lendário, o próprio Cavaleiro Davion viu-se enfrentando um oponente desapontador: o temido Slyrak cresceu velho e frágil. As suas asas, esfarrapadas, as suas poucas escamas que sobraram, apodrecendo, as suas presas, enfraquecidas, e o seu sopro de fogo não ameaçava nada mais do que um pacote de palitos de fósforos molhados. Vendo que não havia honra em assassinar tal criatura, o Cavaleiro Davion preparava-se para dar as costas e deixar o seu velho adversário morrer em paz. Mas uma voz rastejou nos seus pensamentos... Era Slyrak, que fazia um apelo sussurrante para que Davion honrasse-o com uma morte em combate. Davion aceitou, e viu-se ser recompensado muito além do que imaginava pelo seu ato de misericórdia: enquanto mergulhava a sua espada no peito de Slyrak, o dragão atravessava a garganta de Davion com uma garra. Enquanto os seus sangues se misturavam, Slyrak enviou o seu poder através da rota de sangue, transmitindo toda a sua força e séculos de sabedoria ao cavaleiro. A morte do dragão selou o elo entre os dois, e assim nascera o Dragon Knight. O poder ancestral adormece no Cavaleiro Dragão Davion, despertando quando é chamado. Ou talvez seja o dragão quem chama o cavaleiro...	', 'dragon-knight.jpg', '2018-09-04 18:15:19', 1, 1),
(33, 'Drow Ranger', 'O nome de nascença da Drow Ranger é Traxex – um nome bem apropriado a uma cria do povo Drow, baixinhos, de aparência similar a de trolls e de certa forma repulsivos. Mas Traxex não é uma verdadeira Drow. Os seus pais eram viajantes numa caravana atacada por bandidos, cuja matança barulhenta de inocentes despertou a cólera do sossegado povo Drow. Depois de acabada a batalha, os Drow descobriram uma menina escondida nas carroças arruinadas e concordaram que ela não podia ficar abandonada. Mesmo enquanto criança, Traxex mostrou-se naturalmente competente nas artes que prezavam: furtividade, silêncio e sutileza. Em espírito, se não fisicamente, ela poderia ter sido uma Drow órfã que agora retornava à sua casa. Mas à medida que crescia, ela erguia-se mais alta que a sua família e passou a pensar de si mesma como feia. Afinal, a sua feição era macia e simétrica, totalmente desprovida de verrugas e bigodes grosseiros. Afastada da sua tribo adotiva, retirou-se para viver sozinha na floresta. Viajantes perdidos que encontram o seu caminho para fora da floresta falam de uma patrulheira com beleza sem igual que os espreitava das profundezas entre as árvores e então se esvaecia como um sonho antes que eles pudessem se aproximar. Ágil e furtiva, de um calor congelante, ela se move como uma névoa em silêncio. Aquele sussurro que se ouve são as suas flechas congelantes encontrando o coração de um inimigo.	', 'drow-ranger.jpg', '2018-09-04 18:15:46', 2, 1),
(34, 'Earthshaker', 'Como um golem ou gárgula, o Earthshaker já foi um com a terra, mas agora anda livremente sobre ela. Diferente de outras entidades similares, ele criou a si mesmo através de um ato de força de vontade e serve a nenhum outro mestre. Em um sono inquieto, encoberto por uma profunda camada de pedra, ele passou a ter ciência da vida que fluía livremente acima. A curiosidade cresceu dentro dele. Durante uma temporada de tremores, os picos de Nishai abalaram-se em avalanches, mudando o curso de rios e tornando vales rasos em abismos sem fundo. Quando a terra por fim parou de tremer, o Earthshaker saiu da poeira que baixava, sacudindo para os lados pedregulhos maciços como se jogasse para longe um leve cobertor. Tomara a sua forma à imagem de uma fera mortal e nomeara-se Raigor Stonehoof. Agora ele sangra e respira, e, portanto, pode morrer. Mas o seu espírito ainda é aquele da terra; ele leva o seu poder no totem mágico que nunca o deixa. E no dia que ele retornar à poeira, a terra o acolherá como o seu filho pródigo.	', 'earthshaker.jpg', '2018-09-04 18:16:07', 1, 1),
(35, 'Earth Spirit', 'Aprofundado nos penhascos dos planaltos, há um leito de jade sagrado que foi ignorado por muito tempo pelos escavadores das terras altas. Deste material raro, a aparência do grandioso general Kaolin foi esculpida e enterrada em cima de um exército de dez mil homens de pedra – uma força de soldados e sagrados homens, zombadores e acrobatas, todos feitos por artesãos e sepultados há milênios nos confins sombrios da Terra. O que os artesãos não sabiam é que no estranho leito de jade fluía o espírito da Terra – uma força elemental uníssona com o planeta. Quando a força de dentro da jade esculpida encontrou-se desprendida do sangue da vida do mundo, ela reuniu as suas forças ao longo de mil anos e escavou até finalmente libertar-se e banhar-se na luz. Agora o grande Kaolin anda a passos largos nas estradas dos planaltos, lutando pelo espírito da Terra; e em tempos de necessidade invoca resquícios do seu exército sepultado ainda presos no amor do solo.	\r\n', 'earth-spirit.jpg', '2018-09-04 18:16:37', 1, 1),
(36, 'Elder Titan', 'Talvez você se pergunte: \"Como este mundo se formou?\" Por que, de todos os mundos que existem, apenas este tem as suas propriedades estranhas, a sua diversa e heterogênea coleção de criaturas, culturas e tradições? \"A resposta,\" alguém murmura, \"está com os Titãs.\" \r\n\r\nEstes progenitores originais estavam presentes próximos ao Início – se não verdadeiras testemunhas da criação, então nascidos com ela ainda ecoando nos seus ouvidos. Marcados com as energias mais primitivas do universo, não desejavam outra coisa senão continuar eles mesmos como criadores. Desta forma, dedicaram-se à tarefa de moldar a matéria ao seu desejo; martelando e aquecendo, dobrando e soprando. E quando a matéria provou-se menos desafiadora do que gostariam, viraram as suas ferramentas para si mesmos, remodelando as suas mentes e reforjando os seus espíritos até que se tornassem seres de grande resistência. A própria realidade tornou-se o maior objeto da sua metalurgia. Mesmo assim, durante o processo, algumas vezes erravam. Em casos de grande ambição, erros eram inevitáveis. \r\n\r\nAquele que conhecemos como Elder Titan era um grande inovador, um que estudou na forja da criação. Enquanto ele afiava as suas habilidades, despedaçou algo que não poderia nunca ser reparado, apenas jogado fora. Ele caiu no seu próprio mundo quebrado, ele mesmo uma alma despedaçada. Ali ele viveu com os estilhaços cortantes e planos fissurados, além de outros fragmentos perdidos que se espalharam pelas rachaduras no universo primitivo. E é por isso que o mundo que conhecemos se assemelha a uma ilha de náufragos, sobreviventes de um naufrágio há muito esquecido. Isto é, esquecido por todos menos Aquele que culpa a si mesmo. Ele emprega o seu tempo sempre em busca de uma forma de empreender os reparos, para que possa reunir os pedaços da sua alma quebrada, para que nós e todo o mundo possamos ser remendados. Este é Aquele que conhecemos como Elder Titan.	', 'elder-titan.jpg', '2018-09-04 18:20:44', 1, 1),
(37, 'Ember Spirit', 'Perdida nos confins das Montanhas da Lamentação, a Fortaleza Flamejante permanece abandonada. As salas de treinamento, vazias. O pátio, coberto de folhas e poeira. Dentro do seu selado templo, há um estrado. Sobre esse estrado, há um caldeirão de topázio repleto de cinzas ancestrais, resquícios de uma pira funerária do poeta-guerreiro Xin. Por três gerações, Xin ensinou aos seus acólitos os Vínculos da Flama Guardiã, uma série de meditações que treinam a mente e corpo para a dura realidade que ocorre além dos muros da fortaleza. No entanto, ao ensinar o caminho a um guerreiro, ele obteve a rivalidade do próprio e quando se tornou maduro o suficiente, Xin fora superado e morto. Os seus seguidores se espalharam pelo vento. À medida que os anos se tornaram séculos e os seguidores, descendentes, os seus ensinamentos continuaram a existir através de sutis sussurros e ações. Tocado pelo legado milenar do professor, o Celestial Ardente, curioso aspecto do fogo, enviou-se à Fortaleza Flamejante para reacender as cinzas da pira. Destas brasas brilhantes emergiu uma imagem de Xin, embalsamado em fogo, o seu semblante pensativo preparado para treinar e ensinar, para espalhar as chamas do saber por todos que buscam orientação.	', 'ember-spirit.jpg', '2018-09-04 18:21:08', 2, 1),
(38, 'Enchantress', 'Aiushtha parece ser uma criatura inocente e incauta das florestas e, por mais que isso seja completamente verdade, dificilmente é a totalidade da sua história. Ela compreende muito bem o sofrimento do mundo natural. Já vagueou longe e percorreu florestas esplendorosas e sombrias, em todos os climas e todas as estações, reunindo amigos, partilhando novidades, trazendo gargalhadas e curando aonde quer que fosse. Pois em mundos destruídos pela guerra, florestas são aplainadas para que se construam navios e motores de cerco; e até em sítios pacíficos, as florestas eram despojadas para a construção de casas, e como combustível para lareiras incontáveis. Aiushtha ouve as preces de criaturas pequenas, da gente furtiva que precisa de sombra verde e cobertura feita de folhas. Ela carrega as suas histórias da selva ao mundo, acreditando que o seu próprio ânimo é um tipo de encantamento, que pode por si próprio cumprir a promessa de um futuro verdejante.	', 'enchantress.jpg', '2018-09-04 18:21:29', 3, 1),
(39, 'Enigma', 'Nada se sabe sobre o passado do Enigma. Existem apenas histórias e lendas, a maioria delas apócrifas, passadas através das eras. Na verdade, o Enigma é um mistério cuja única biografia verdadeira é a descrição: ele é uma força universal, um consumidor de mundos. Ele é um ser do vazio, às vezes corpóreo, outras vezes etéreo. Uma besta entre os planos. Há histórias que dizem que ele era um grande alquimista que tentou desvendar os segredos do universo e acabou sendo amaldiçoado pela sua arrogância. Outras lendas dizem que ele é um ser antigo de gravidade estranha, o abismo personificado – uma voz distorcida de fora da escuridão original, anterior à primeira luz do universo. E há lendas mais antigas que dizem que ele é a primeira estrela que desabou, um buraco negro que se tornou complexo e consciente – as suas motivações incompreensíveis, o seu poder inexorável, uma força de destruição desencadeada sobre a existência em si.	', 'enigma.jpg', '2018-09-04 18:21:52', 3, 1),
(40, 'Faceless Void', 'Darkterror, o Faceless Void, é um visitante de Claszureme, um reino onde o tempo não existe. Ainda é um mistério a razão pela qual este ser de outra dimensão acredita que a luta pelas Pedras Nêmesis vale a entrada ao nosso plano físico, mas, aparentemente, um distúrbio no equilíbrio do poder deste mundo tem repercussões nas dimensões adjacentes. O tempo não interessa para Darkterror, exceto como um meio de frutrar os seus inimigos e de ajudar os seus aliados. O seu vasto conhecimento do cosmos deu-lhe uma qualidade remota e desconexa, embora na batalha ele é bem capaz de torná-la pessoal.	', 'faceless-void.jpg', '2018-09-04 18:23:02', 2, 1),
(41, 'Grimstroke', 'The people of Ashkavor crowded around the temple square, eager to witness the ascension of their new guardian -- to stand near the man as he bound their souls to his own. But as his final brush strokes fell against the runestone, and the bond of a new Ascended One was forged, everyone -- even those who\'d stayed in their homes -- could sense that something had gone terribly wrong.\r\n\r\nHe knew the cause instantly. The droplets of ichor he\'d procured to amplify the potency of his inkpots had instead contaminated them, and the power of the binding spell he\'d cast now threatened to consume him. An inky corruption snaked upward from the runestone, along the handle of his brush, soon overtaking his hands. From there it spread quickly. Once it overcame his face and his mouth, he couldn\'t have screamed even if he\'d wanted to.\r\n\r\nAll of his life he\'d calculated on how to attain ever greater powers than the limits presented by his teachers would allow--going so far as to break the sacred prohibition against augmenting the inks. Indeed, with the wellspring of the Ascended bond open to him, he felt a measure of power coursing into his soul like he\'d never imagined. His greatest triumph was upon him, if he could only survive it.\r\n\r\nHe drew deep from the power of the bond, pushing back against the corrupted ink flow. A great moan filled the air -- the collective cry of his people. Some swayed on their feet. The weakest collapsed. Many tried to run. And still deeper he pulled from their bloodline reservoir. But it wasn\'t enough to stop the ink tide.\r\n\r\nIt was only when the breath trapped in his lungs began to fail him, and the inkpool darkness fully encased him, that he saw his way out. The bond he\'d made with the Ashkavoran people -- his people -- meant to be drawn upon only in service of their protection... It flowed two ways.\r\n\r\nWith a final surge of strength -- this time directed by more than just blind repulsion -- he pushed the ink torrent into the bond itself.\r\n\r\nSlowly, he felt the tide retreat... and heard the awful wails of his people as the corruption in turn rolled over them. When at last the ink relented, his eyes opened upon a world changed. The Ashkavoran people as he knew them were gone. Every last soul was transformed into terrifying shades of their former selves -- comprised no longer of blood and bone, only viscid, tainted ink.	', 'grimstroke.jpg', '2018-09-04 18:23:27', 3, 1);

-- --------------------------------------------------------

--
-- Estrutura da tabela `usuarios_tb`
--

CREATE TABLE `usuarios_tb` (
  `id` int(11) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `senha` varchar(255) NOT NULL,
  `data_cadastro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `usuarios_tb`
--

INSERT INTO `usuarios_tb` (`id`, `nome`, `email`, `username`, `senha`, `data_cadastro`) VALUES
(1, 'Lucas Genari', 'lucas@email.com', 'lucasgenari', '202cb962ac59075b964b07152d234b70', '2018-08-30 12:06:54');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categorias_tb`
--
ALTER TABLE `categorias_tb`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `herois_tb`
--
ALTER TABLE `herois_tb`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `usuarios_tb`
--
ALTER TABLE `usuarios_tb`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categorias_tb`
--
ALTER TABLE `categorias_tb`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `herois_tb`
--
ALTER TABLE `herois_tb`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT for table `usuarios_tb`
--
ALTER TABLE `usuarios_tb`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
