version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_app
    volumes:
      - .:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: code_dota_db
    restart: always
    environment:
      MYSQL_USER: gabigol
      MYSQL_PASSWORD: teste_admin
      MYSQL_DATABASE: projetinho
    ports:
      - "3306:3306"  # Porta alterada para 3308
    volumes:
      - db_data:/var/lib/mysql
      # - ./cidota.sql:/docker-entrypoint-initdb.d/cidota.sql  # Script SQL de inicialização
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
