# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_dota
    volumes:
      - .:/var/www/html
    ports:
      - "8088:80"  # Porta alterada para 8088
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: codeigniter_dota_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Senha do root (necessário para iniciar o MySQL)
      MYSQL_USER: gabigol
      MYSQL_PASSWORD: teste_admin
      MYSQL_DATABASE: projetinho
    ports:
      - "3308:3306"  # Porta do MySQL alterada para 3308
    volumes:
      - db_data:/var/lib/mysql
      - ./cidota.sql:/docker-entrypoint-initdb.d/cidota.sql  # Script SQL opcional
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
